name: Run deck
on: push
jobs:
  deck-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: "1.19.1"
      - name: Clone repo
        uses: actions/checkout@v2
      - name: run deck deck-diff
        run: deck diff --kong-addr http://43.192.63.10:8001/

  deck-sync:
    needs: deck-diff
    environment: productions
    runs-on: ubuntu-latest
    steps: 
      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: "1.19.1"
      - name: Clone repo
        uses: actions/checkout@v2
      - name: run deck deck-sync
        run: deck sync --kong-addr http://43.192.63.10:8001/